# ezserve configuration file
# Save this as .ezserve.toml in your project directory

# Server settings
port = 8000
bind = "127.0.0.1"
root = "."

# Features
single_page = false
cors = false
no_dirlist = false
log_json = false
watch = false
gzip = true

# Performance
threads = 4

# Example configurations:
# For development:
# port = 3000
# cors = true
# watch = true
# gzip = true

# For production:
# port = 80
# bind = "0.0.0.0"
# gzip = true
# log_json = true
# threads = 16